/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import static finalproject.AddStudent.connection;
import static finalproject.AddStudent.stmt;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import java.sql.*;

/**
 *
 * @author Lyudmila
 */
public class AddFromCsv extends javax.swing.JFrame {
    javax.swing.JFrame menu;
    public static Statement stmt;
    public static Connection connection;
    private static ResultSet rs;
    String filename;
    String urlDB, login, password;
    /**
     * Creates new form AddFromTxt
     */
    public AddFromCsv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPanelErrors = new javax.swing.JTextPane();
        jButtonStart = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        fileChooser.setDialogTitle("Выбор файла");
        fileChooser.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentsDB");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPanelErrors.setEditable(false);
        jTextPanelErrors.setBorder(null);
        jTextPanelErrors.setForeground(new java.awt.Color(255, 255, 255));
        jTextPanelErrors.setToolTipText("");
        jTextPanelErrors.setCaretColor(new java.awt.Color(153, 153, 153));
        jTextPanelErrors.setDisabledTextColor(new java.awt.Color(153, 0, 0));
        jTextPanelErrors.setEnabled(false);
        jTextPanelErrors.setFocusCycleRoot(false);
        jTextPanelErrors.setFocusable(false);
        jTextPanelErrors.setOpaque(false);
        jTextPanelErrors.setRequestFocusEnabled(false);
        jTextPanelErrors.setSelectionColor(new java.awt.Color(204, 204, 204));
        jTextPanelErrors.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextPanelErrors);

        jButtonStart.setText("Начать добавление");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonBack.setText("Назад");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Выберите csv файл, содержащий записи о новых студентах.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 120, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 121, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        // What to do with the file, e.g. display it in a TextArea
        //jTextPanelErrors.read( file.getName(), null );
        filename = file.getAbsolutePath();
        jTextPanelErrors.setText("Файл " + file.getName() + " выбран");
        //appendToTextPanel(jTextPanelErrors, file.getName());
    } else {
        System.out.println("File access cancelled by user.");
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        try {
            BufferedReader read = new BufferedReader(new FileReader(filename));
            String data;
            String strSubj;
            PreparedStatement prstmt;
            //connection = DriverManager.getConnection(ConnectionDB.url, ConnectionDB.login, ConnectionDB.pass);
            ConnectionDB db_conn = ConnectionDB.getConnectionDB();
            stmt = db_conn.connection.createStatement();
            int count = 0;
            while ((data = read.readLine()) != null) {
                appendToTextPanel(jTextPanelErrors, "\n" + data);
                String[] value = data.split(";");
                
                try {
                    if (value.length != 6)
                        throw new Exception("Неверное количество столбцов записи " +value.length + " - строка " + count);
                    StudentData student = new StudentData(value[0], value[1], value[2], value[3], value[4], value[5]);
                    if (student.msg.isEmpty()){
                        prstmt = connection.prepareStatement("Insert into " + ConnectionDB.db_name + ".Students Values(?, ?, ?, ?, ?, ?)");
                        prstmt.setInt(1, Integer.parseInt(student.id));
                        prstmt.setString(2, student.lastname);
                        prstmt.setString(3, student.name);
                        prstmt.setString(4, student.number);
                        prstmt.setString(5, student.city);
                        prstmt.setString(6, student.university);
                        prstmt.executeUpdate();
                        prstmt.close();
                    } else {
                        appendToTextPanel(jTextPanelErrors, "\n" + student.msg);
                    }    
                } catch (Exception e) {
                    //jTextPanelErrors.setText(jTextPanelErrors.getText() + e.getMessage() + "\n");
                    appendToTextPanel(jTextPanelErrors, "\n" + e.getMessage());
                }
                count++;
            }
            
        } catch (Exception e) {
            jTextPanelErrors.setText("Ошибка импорта файла: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        menu = new MenuJFrame();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    public void appendToTextPanel(JTextPane jtp, String s) {
   try {
      Document doc = jtp.getDocument();
      doc.insertString(doc.getLength(), s, null);
   } catch(BadLocationException exc) {
      exc.printStackTrace();
   }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFromCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFromCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFromCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFromCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFromTxt().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFromTxt().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPanelErrors;
    // End of variables declaration//GEN-END:variables
}
